/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Wed Apr 13 13:07:59 2016. */

#include "Radio.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t RadioProtocolWrapper_fields[4] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, RadioProtocolWrapper, command, command, &RadioProtocolCommand_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, RadioProtocolWrapper, robotsettings, command, &RobotSettings_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, RadioProtocolWrapper, basesettings, robotsettings, &BasestationSettings_fields),
    PB_LAST_FIELD
};

const pb_field_t RadioProtocolCommand_fields[9] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, RadioProtocolCommand, robot_id, robot_id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, RadioProtocolCommand, velocity_x, robot_id, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, RadioProtocolCommand, velocity_y, velocity_x, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, RadioProtocolCommand, velocity_r, velocity_y, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, RadioProtocolCommand, flat_kick, velocity_r, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, RadioProtocolCommand, chip_kick, flat_kick, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, RadioProtocolCommand, dribbler_spin, chip_kick, 0),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, RadioProtocolCommand, distance, dribbler_spin, 0),
    PB_LAST_FIELD
};

const pb_field_t BasestationSettings_fields[2] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, BasestationSettings, frequency, frequency, 0),
    PB_LAST_FIELD
};

const pb_field_t RobotSettings_fields[3] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, RobotSettings, robot_id, robot_id, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, RobotSettings, request, robot_id, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(RadioProtocolWrapper, command) < 65536 && pb_membersize(RadioProtocolWrapper, robotsettings) < 65536 && pb_membersize(RadioProtocolWrapper, basesettings) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_RadioProtocolWrapper_RadioProtocolCommand_BasestationSettings_RobotSettings)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(RadioProtocolWrapper, command) < 256 && pb_membersize(RadioProtocolWrapper, robotsettings) < 256 && pb_membersize(RadioProtocolWrapper, basesettings) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_RadioProtocolWrapper_RadioProtocolCommand_BasestationSettings_RobotSettings)
#endif


/* @@protoc_insertion_point(eof) */
