/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Wed May 24 15:18:18 2017. */

#include "robot.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Command_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Command, id, id, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, Command, move, id, &Command_Move_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, Command, action, move, &Command_Action_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, Command, settings, action, &Command_Setting_fields),
    PB_LAST_FIELD
};

const pb_field_t Command_Move_fields[4] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, Command_Move, x, x, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, Command_Move, y, x, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, Command_Move, r, y, 0),
    PB_LAST_FIELD
};

const pb_field_t Command_Action_fields[4] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, Command_Action, dribble, dribble, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, Command_Action, kick, dribble, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, Command_Action, chip, kick, 0),
    PB_LAST_FIELD
};

const pb_field_t Command_Setting_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Command_Setting, id, id, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, Command_Setting, name, id, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, Command_Setting, value, name, 0),
    PB_LAST_FIELD
};

const pb_field_t Measurements_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Measurements, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, Measurements, measurements, id, &Measurements_Single_fields),
    PB_LAST_FIELD
};

const pb_field_t Measurements_Single_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, Measurements_Single, label, label, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, Measurements_Single, value, label, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, Measurements_Single, tenFoldMultiplier, value, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Command, move) < 65536 && pb_membersize(Command, action) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Command_Command_Move_Command_Action_Command_Setting_Measurements_Measurements_Single)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Command, move) < 256 && pb_membersize(Command, action) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Command_Command_Move_Command_Action_Command_Setting_Measurements_Measurements_Single)
#endif


/* @@protoc_insertion_point(eof) */
